apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pq8au1n5h-python 
  janus-idp.io/tekton: pq8au1n5h-python
  backstage.io/kubernetes-id: pq8au1n5h-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pq8au1n5h-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml