apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: pq8au1n5h-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:1b4a0305fe5a40b15778f85cb74e5ddef13adeef@sha256:872baa9e6098313f184f2ee8aa66799b9af29de9100d12d5bb751736829a2dca
          name: container-image
